add-xdebug: done

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,6 +1,13 @@
-FROM php:8.2-fpm-alpine
+FROM php:8.2-fpm-alpine as app
 
-RUN docker-php-ext-install pdo pdo_mysql
+# Useful PHP extension installer image, copy binary into your container
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
+
+# RUN docker-php-ext-install pdo pdo_mysql
+# install php extensions
+# exit on errors, exit on unset variables, print every command as it is executed
+RUN set -eux;  \
+    install-php-extensions pdo pdo_mysql;
 
 # allow super user - set this if you use Composer as a
 # super user at all times line in docker containers
@@ -25,3 +32,12 @@ COPY ./app .
 
 # run composer dump-autoload --optimize
 RUN composer dump-autoload --optimize
+
+FROM app as app_dev
+
+ENV XDEBUG_MODE=off
+
+COPY ./php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
+
+RUN set -eux;  \
+    install-php-extensions xdebug;
